spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  datasource:
    driver-class-name: org.postgresql.Driver 
    url: jdbc:postgresql://localhost:5432/student
    username: postgres
    password: postgres
    
  mail:
    host: smtp.gmail.com
    port: 587
    username: asiansea0504@gmail.com
    password: auyygqvpclijczgr
    properties.mail.smtp.auth: true
    properties.mail.smtp.starttls.enable: true